### PR TITLE
Added request parameters type and key to /metrics

### PR DESCRIPTION
**Pull request by srini156**
Added request parameters ``type`` and ``key`` to ``/metrics``.

### CODE REVIEW

**Comment by srini156** [comment]
@ryantenney Any updates on this PR?

**Comment by srini156** [comment]
Thanks @ryantenney  :)

**Comment by srini156** [comment]
@ryantenney  - Any updates on when this feature will be released?

**Comment by ryantenney** [comment]
Not soon, it's on deck for v4, which might happen at earliest later this year.  If you apply this to the 3.2-development branch and open a pull request I'd be happy to merge it there as well, that should be out in a couple months, tops!

**Pull request merged**
