### PR TITLE
Initial commit of the metrics-collectd plugin.

### PR DESCRIPTION
**Pull request by timezra**
This is a pull request for adding a new metrics reporter that uses the collectd binary protocol over UDP (https://github.com/dropwizard/metrics/issues/853).
I have been in a situation where I funnel many of my application and reporting metrics through a 3rd-party tool (which has an input codec for collectd over UDP along with a bunch of other protocols), and there appears to be a conflict between the UDP listener that gathers collectd data from the standard collectd plugins and both the listener for metrics logs or the graphite listener that pulls in metrics data from the graphite reporter.
This collectd reporter is an attempt to put metrics data and collectd data on even footing when it is pulled into a 3rd-party tool.
Perhaps someone else will find it useful as well.

### CODE REVIEW

**Comment by dernasherbrezon** [comment]
Haha. Looks like we both implemented collectd support:

**Comment by dernasherbrezon** [comment]
https://github.com/dropwizard/metrics/pull/871

**Comment by vincentbernat** [comment]
Is there any reason that both this PR and #871 are not moving forward anymore?

**Comment by ryantenney** [comment]
@timezra I greatly appreciate the PR. I just merged #871, which added a collectd reporter, based solely on the fact that it was mergeable as-is. If it missed out on any features that your PR contained, please let me know and I'll be happy to remedy that.

**Pull request closed without merging**
