### PR TITLE
Refactor influxdb reporter to use Apache HttpClient

### PR DESCRIPTION
**Pull request by davidkarlsen**
A drop-in replacement for the current url-based impl.
However I'd like to "structure" the configuration better, and take username, password parameters instead of an username:pw authstring. WDYT?

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Also - what do you think about excluding commons-logging from the http client, and use jcl-over-slf4j instead as slf4j seems to be the logging framework in use?

**Comment by davidkarlsen** [comment]
Ping - any thoughts on this?

**Comment by ryantenney** [comment]
Looks pretty good, thanks! I definitely agree about excluding commons-logging.

**Comment by davidkarlsen** [comment]
OK - then I'll fix that - what about splitting the auth string into username and password properties?

**Comment by ryantenney** [comment]
Definitely, and don't worry about constructor binary compatibility.

**Comment by davidkarlsen** [comment]
Fixed - can you pull this and I'll fix the spring-metrics as well?

**Comment by davidkarlsen** [comment]
@ryantenney Maybe this can be pulled now and I can then fix spring-metrics after this as well?

**Comment by ryantenney** [comment]
Thanks! Sorry I missed your comment the other day.

**Pull request merged**
