### PR TITLE
Add different moving average implementations to Meter

### PR DESCRIPTION
**Pull request by pe-st**
I propose to add a different moving average to meter (in fact the change aims to allow to plug-in any moving average implementation, similar to the Histogram metrics where you can provide different Reservoirs).

My use case is to monitor an online transaction system with hundreds or thousands per seconds and a rate-per-minute metric is exactly what I need.
However I want exact numbers per minute and no influence from past minutes as the exponentially decaying default implementation has; when the number of transactions drops to zero this must be clearly visible.

I'm aware of https://github.com/vladimir-bukhtoyarov/rolling-metrics but would like to keep the Meter interface for easy integration into tools.
The Meter interface is a good model for what I'd expect, it's just the Unix `top` behaviour that doesn't fit my needs.

This feature has already been requested directly ([Feature request: Record and query the past n-minutes rate of an event](https://github.com/dropwizard/metrics/issues/1125)) and indirectly (by requesting resettable metrics; a simple moving average is nothing else than having three counter that are reset automatically after one, five and fifteen minutes):

- [JMX reset operation on metrics](https://github.com/dropwizard/metrics/issues/143)
- [Adds a reset() method to Meter and Timer](https://github.com/dropwizard/metrics/pull/193)
- https://stackoverflow.com/questions/38132551/dropwizard-metrics-how-to-reset-counters-after-reporting-interval
- https://stackoverflow.com/questions/39198572/codahale-metrics-counter-reset-and-count-everyday

### CODE REVIEW

**Comment by pe-st** [comment]
I tried to reduce the codeclimate issues a bit. There are some issues left, but I'm not sure that it makes sense to address them, I would mark them as false positives (i.e. the legibility of the code could suffer by further refactorings) or legacy (i.e. they were in the code before my pull request).

If you find my PR useful, I can also update the documentation (`docs/source/manual/core.rst`)

**Comment by wudan3551** [comment]
i have same demands, and i think a pluggable Meter is better!

**Comment by pe-st** [comment]
The current travis build with Java 11.0.2 fails due to a problem with javadoc:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project metrics-annotation: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] 
[ERROR] Command line was: /home/travis/openjdk11/bin/javadoc @options @packages
```

This problem seems to be a problem with JDK or the maven-javadoc-plugin and was already reported elsewhere without known workaround, e.g.

* https://github.com/oracle/opengrok/issues/2629
* https://bugs.openjdk.java.net/browse/JDK-8212233
* https://issues.apache.org/jira/browse/MJAVADOC-555

**Comment by pe-st** [comment]
After merging the fix for Javadoc with Java 11 (Commit 9894180c) the build is green again.

The PR didn't get much attention from the maintainers yet (either positive or negative). Can I improve something? Should I squash the commits to have a shorter history? Or is proposing a PR not the preferred way to contribute?

Kind Regards, Peter

**Pull request merged**
