### PR TITLE
Merge changes from the 3.1 branch to 3.2

### PR DESCRIPTION
**Pull request by arteam**
Merge changes from the 3.-maintenance branch to the 3.2 branch

### CODE REVIEW

**Comment by arteam** [comment]
We actually interested only in the last commits plus some docs update,

**Comment by jgangemi** [comment]
may i ask why the `cpu profiling` support change got reverted? i was looking forward to using that.

**Comment by arteam** [comment]
It is available in the 3.2 branch. It was originally submitted by a mistake to the 3.1 branch and then reverted. The revert commit shows up on the merge, but if you take a look at the diff, no CPU profiling changes are reverted.

**Comment by jgangemi** [comment]
thanks for the clarification!!

**Pull request merged**
