### PR TITLE
Add statistics metric

### PR DESCRIPTION
**Pull request by tkp1n**
Add a statistics metric to keep track of values which are strictly monotonically nondecreasing.
Neither Histogram nor Counter support setting new values.
Statistics fills this gap.

### CODE REVIEW

**Comment by thattolleyguy** [comment]
How is this different than a counter besides that it's non decreasing?

**Comment by ryantenney** [comment]
@tkp1n `Gauge` already supports this functionality, though I appreciate your contribution!

**Comment by tkp1n** [comment]
With a Gauge you provide a callback which is evaluated when the gauge is measured.
I'd like to be able to explicitly set the value (like a Counter#inc()). To have a metric for values which I receive from an external source and which are unfortunately nondecreasing.

**Comment by ryantenney** [comment]
From my reading of the code, `Statistic` doesn't enforce that the values are nondecreasing.
As `Gauge` is an interface you can create a `Statistic` or `SettableGauge` class which implements it:

```java
public class Statistic implements Gauge<Long> {
    private Long value;
    public Long getValue() {
        return value;
    }
    public void setValue(Long value) {
        this.value = value;
    }
}
```

**Pull request closed without merging**
