### PR TITLE
[jvm] make OSGi Package-Import for com.sun.management optional

### PR DESCRIPTION
**Pull request by vorburger**
requested in https://jira.opendaylight.org/browse/INFRAUTILS-41

### CODE REVIEW

**Comment by arteam** [comment]
LGTM. I believe we use the `com.sun.management` package only in `FileDescriptorRatioGauge`, which is part of `metrics-jvm`, so it should be fine to make it optional.

**Comment by arteam** [comment]
@vorburger If you want, I can cut a 4.0.3 release with this change.

**Comment by vorburger** [comment]
@arteam it would be very cool and much appreciated if you could cut a 4.0.3 release - we would test and use it!

**Comment by splatch** [comment]
@arteam, @vorburger any plans to cut 4.0.3 any time soon? ;-) I've just hit this one.

**Comment by arteam** [comment]
Thanks for the reminder, I will cut a release today.

**Comment by splatch** [comment]
@arteam thank you very much for cutting release :hand:!

**Pull request merged**
