### PR TITLE
Modify Timer.Context for Extensibility

### PR DESCRIPTION
**Pull request by vjkoskela**
Change Timer.Context constructor to protected from private so that the class may be extended.

### CODE REVIEW

**Comment by ryantenney** [comment]
What's your use case for this? I generally avoid expanding visibility if not absolutely critical.

**Comment by vjkoskela** [comment]
I completely agree. We are writing an interop layer between our library and Codahale metrics. Code already using Codahale metrics will be able to output data through our library. We need to create an instance of Timer.Context in order to satisfy the contract of Codahale's Timer in our library where we subclass Timer. Internally, this is being used in an extension of DropWizard to get it to interoperate with existing metrics infrastructure. Happy to discuss this further if you would like more details.

**Comment by vjkoskela** [comment]
@ryantenney any further thoughts on this?

**Comment by ryantenney** [comment]
First class support for custom metrics is one of my priorities for Metrics 4. As you know, as of Metrics 3, custom metric types aren't supported, and understandably you're trying to work around that. I've decided that I don't want to start making changes to things in 3 to allow hacking in custom metric types.

**Comment by vjkoskela** [comment]
Fair enough. Is there a mailing list or issue I can subscribe to for updates about the release of version 4?

**Comment by ryantenney** [comment]
There's the metrics-user group, but there hasn't been much in the way of conversation about v4 yet. I do need to start engaging the group on discussions about v4 priorities. https://groups.google.com/forum/#!forum/metrics-user

**Pull request closed without merging**
