### PR TITLE
Implement doOptions for CORS in MetricServlet

### PR DESCRIPTION
**Pull request by karlr42**
Set Access-Control-Allow-Origin on Options response headers if allowedOrigin is specified by a ContextListener.

Related to #1120

### CODE REVIEW

**Comment by karlr42** [comment]
I know you will want me to write a test, I'm just working on that now.

**Comment by osigida** [comment]
I guess CORS headers should be managed differently, something like described here
http://jitterted.co.technology/tidbits/2014/04/04/handling-cors-in-dropwizard-and-jetty/

**Comment by karlr42** [comment]
I will try that, but then what was the point of adding the ability to set Access-Control-Allow-Origin at the MetricsServlet level in #440 in the first place?

**Comment by karlr42** [comment]
OK, so for my specific use case, using Tomcat, I actually was able to solve this by editing my web.xml
````
<filter>
	<filter-name>MetricsCorsFilter</filter-name>
	<filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
	<init-param>
    	<param-name>cors.allowed.origins</param-name>
    	<param-value>*</param-value>
    </init-param>
  </filter>
  <filter-mapping>
	<filter-name>MetricsCorsFilter</filter-name>
  	<url-pattern>/metrics/*</url-pattern>
  </filter-mapping>
````
So, using my application's server to handle CORS, like described in your link. This seems to work fine, it sets the appropriate headers on my OPTIONS requests. So I suppose this PR might not be needed.

But I still have the question, what is the point of setting Access-Control-Allow-Origin on the MetricsServlet directly? It doesn't seem like it would actually work because it doesn't support the OPTIONS method. It seems the correct way to do this is to set it up on Jetty/Tomcat/whatever, instead of the servlet, so maybe it makes sense to just remove this option entirely.

**Comment by osigida** [comment]
@karlr42 good to know that it worked for you! 
I'm not sure why it was introduced... as main idea is to remove such a functionality form general endpoints (like metrics, swagger, etc) and handle it on the application level, where you can manage it based on your specific requirements.

**Comment by arteam** [comment]
Please reopen if the issue still exists.

**Pull request closed without merging**
