### PR TITLE
Sanitize names sent to graphite

### PR DESCRIPTION
**Pull request by thattolleyguy**
Enhancing the sanitizer to remove other characters that aren't allowed. Any illegal character is replaced with a dash. @ryantenney

### CODE REVIEW

**Comment by nickbabcock** [comment]
Why the trailing `.` at the end of the regex, which makes it different than the regex in https://github.com/dropwizard/metrics/issues/637#issuecomment-63964756? Your solution won't change `foo@bar.com` (the period is significant to graphite!). Dropping the period from the regex will change the previous example to `foo@bar-com`

**Comment by nickbabcock** [comment]
With #936 merged, should this be closed?

**Comment by Grundlefleck** [comment]
Hi, 

I just came across this issue (happened to try 3.2.2 and 4.0.2) and it has not been addressed by #936. At first glance it looks like extending the disallowed characters, from only '-' to also exclude apostrophes would have avoided the issue. 

How this manifested for me is that from the metrics-jvm module, using Java 9, the MemoryUsageGaugeSet emits metrics prefixed with: 
 - `jvm.memory.pools.CodeHeap-'non-nmethods'.`
 - `jvm.memory.pools.CodeHeap-'non-profiled-nmethods'.`
 - `jvm.memory.pools.CodeHeap-'profiled-nmethods'.`

I have a workaround for this particular issue[0] but a generic replacement of any invalid characters would have been great.

Is there any chance of getting this PR revived, or should I submit something similar based off more recent code?

---
[0] these are the only offending metrics I've noticed out of the modules we use, and I have chosen to drop the metrics like so:
```
registry.register("jvm.memory", new MemoryUsageGaugeSet(
  ManagementFactory.getMemoryMXBean(),
  ManagementFactory.getMemoryPoolMXBeans().stream().filter(bean -> !bean.getName().contains("'")).collect(toList())));
```

**Comment by maxmil** [comment]
Referencing the same issue https://github.com/dropwizard/metrics/issues/1322

**Pull request closed without merging**
