### PR TITLE
Release/5.0.x merge 4.2.x

### PR DESCRIPTION
**Pull request by DanyBv**
Merge branch 'release/4.2.x' into release/5.0.x

### CODE REVIEW

**Comment by DanyBv** [comment]
@joschi Thought I'd help by syncing 5.0.x with 4.2.x and contributing to Metrics5. I hope the project will see the light of day and I can contribute to it if you ever need.

**Comment by DanyBv** [comment]
> @joschi Thought I'd help by syncing 5.0.x with 4.2.x and contributing to Metrics5. I hope the project will see the light of day and I can contribute to it if you ever need.

@joschi I shouldn't have brought all the 4.2 branch commits and just the code changes. Like in this commit: https://github.com/dropwizard/metrics/commit/f75c56be7d1d71692a206dcd5a03a4427cffd8fb. Sorry for the setback.

**Comment by joschi** [comment]
@DanyBv Are there any specific changes you'd like to get from the `release/4.2.x` branch into the `release/5.0.x` branch?

For dependency updates, @renovate-bot usually takes care of creating PRs for every release branch.
https://github.com/dropwizard/metrics/blob/65ca673f232a76c5b5a2305c1861f8f03bbcf786/renovate.json#L6

**Comment by joschi** [comment]
@DanyBv I might have been a bit too rash to close this PR.

Since you already made the effort, I'm also happy to reopen it. 👍

**Pull request closed without merging**
