### PR TITLE
Register metrics defined at Resource level

### PR DESCRIPTION
**Pull request by patrox**
If a `Resource` class is annotated with either:

* `@Timed`,
* `@Metered`
* `@ExceptionMetered`

all method defined in such class will 'inherit' the corresponding annotation.

### CODE REVIEW

**Comment by patrox** [comment]
@ryantenney I was wondering if you could have a look at this PR and let me know if you have any comments (positive or negative) ?

**Comment by ryantenney** [comment]
I certainly will, but I'm very busy right now, I'll get to it soon.

**Comment by patrox** [comment]
@ryantenney Just reminding you about this PR, would really love to get some feedback from you,
so we don't need to keep a separate fork with the change.

**Comment by ryantenney** [comment]
@patrox Thank you, and I'm so sorry for the delay getting this merged.

**Comment by rahuljain1804** [comment]
Hi @ryantenney, I am using metrics-core 3.1.0 for jmx reporting but unable to see @Timed working at resource level. Can you tell me which version supports @Timed at resource level?

**Comment by patrox** [comment]
Hi @ryantenney @arteam,
I'm wondering if the changes from this PR were released as part of some latest releases ?

Cause I checked, and I couldn't find them :( Can you please check ?

**Comment by jplock** [comment]
@patrox this went into `master` and I don't think was cherry-picked into the 3.1 or 3.2 release branches, so we'd have to wait until 4.0 for this one.

**Comment by arteam** [comment]
I will take a look. I moved a bunch of merge requests manually from the 4.0 branch to 3.2, maybe I missed this.

**Comment by patrox** [comment]
thanks @jplock & @arteam, I appreciate your prompt response

**Pull request merged**
