### PR TITLE
Timer.Context now implements AutoCloseable

### PR DESCRIPTION
**Pull request by kilotaras**
Small improvement that allows Timer.Context to be used in try-with-resources

### CODE REVIEW

**Comment by jmason** [comment]
:+1: from a random watcher here -- we do this in our wrapper for Timer.Context and it's really nice.

**Comment by ryantenney** [comment]
I like it. Can you also remove Closeable, or does that cause problems?

**Comment by kilotaras** [comment]
AutoCloseable doesn't implement Closeable (no idea why though). Removing it would be a breaking change.

https://docs.oracle.com/javase/7/docs/api/java/lang/AutoCloseable.html

**Comment by ryantenney** [comment]
Yea, we can live with that. We're working on v4, so breaking changes are welcome.

**Comment by kilotaras** [comment]
Here you go.

**Comment by marshallpierce** [comment]
Closeable extends AutoCloseable, not the other way around, because AutoCloseable allows throwing Exception.

The Closeable imports can be removed now, right?

**Comment by ryantenney** [comment]
I reverted the change to Timer in metrics-adapter, since that module is around for backwards compatibility with 3.x, and we shouldn't do anything that could break it.  Also I removed the Closeable import from Timer in metrics-core.

**Pull request merged**
