### PR TITLE
Introducing a health check filter

### PR DESCRIPTION
**Pull request by arkigabor**
Adding a health check filter similar to metric filter. This will allow registering multiple health check servlets on different endpoints exposing different checks from a single registry. It could be useful when someone wants to distinguish critical checks  - that would signal the application is non-functional - from the less important ones.

### CODE REVIEW

**Comment by arkigabor** [comment]
Will there be another 3.2 release this could fit into?
I'm thinking about looking into JMX health check as well ( #832 ) and this could be useful there too.

**Comment by ryantenney** [comment]
I'm afraid this can't go into 3.2, we (mostly) follow semantic versioning, so we can't change the API without going to 3.3 or 4.0.

**Comment by arkigabor** [comment]
Yeah, I meant 3.x just for some reason wrote 3.2 instead. Rephrasing the question: do you plan any other minor releases before 4.0 or that is the only branch for feature PRs?

**Comment by arteam** [comment]
The next release will be 4.0.0 and we plan only maintenance releases on 3.2.*. I've merged the pull requests against the 4.0-development branch. Thank you!

**Pull request closed without merging**
