### PR TITLE
ability to query individual health checks

### PR DESCRIPTION
**Pull request by osigida**
New feature: ability to query individual health checks

We have few health checks in our application. and one of them is basic dead-lock threads.
When this happens we have no choice than to restart the app.
We would like to automate it but we don't like to query all health checks and then parse the response, because it is useless to call all of them and bring some logic to the monitoring tool. Instead we would like to query individual check and act immediately if its failing.

### CODE REVIEW

**Comment by ryantenney** [comment]
Could you add a test to https://github.com/dropwizard/metrics/blob/master/metrics-servlets/src/test/java/io/dropwizard/metrics/servlets/HealthCheckServletTest.java?

**Comment by osigida** [comment]
@ryantenney I was trying to hack and manage some tests, but the way how the code is organised it is impossible... havy refactoring for health-check servlet is required.

**Comment by ingwarsw** [comment]
Our company also would benefit from such feature..

Any help needed to make it possible?

**Comment by osigida** [comment]
@ingwarsw maybe if you can come up with any kind of unit test? 
we miserably failed to find any way to unit-test this feature.

**Comment by ingwarsw** [comment]
Will try.. 

Do i read correctly that url for test should be in format heatlh/nameOfHealthCheck ?

**Comment by ingwarsw** [comment]
@ryantenney Will it be possible to add it after adding tests and other required stuff or its not desired feature at all?

**Comment by osigida** [comment]
@ingwarsw, right 
there are 2 ways to query it 
`/healthcheck` to query all registered health checks or
`/healthcheck/name_of_healthcheck` to query one of them, example: `/healthcheck/deadlocks`

**Comment by ingwarsw** [comment]
Tests was actually easy :)
I refactored it a bit.. but I dont want to create other PR.

Here it is..
https://github.com/dropwizard/metrics/compare/master...ingwarsw:individual-healthchecks?expand=1

**Comment by osigida** [comment]
the PR is recreated on top of 3.2-development branch 
see https://github.com/dropwizard/metrics/pull/940

**Pull request closed without merging**
