### PR TITLE
METRICS-#663: add support for custom details in HealthCheck.Result

### PR DESCRIPTION
**Pull request by arnaud-deprez**
New pull request on 3.2-development

### CODE REVIEW

**Comment by arnaud-deprez** [comment]
@ryantenney I propose to continue the discussion here.

**Comment by arnaud-deprez** [comment]
@ryantenney here is the new commit with your requested changes.
Rgds

**Comment by colmg** [comment]
very useful, as allows tagging of a health check. Is this ready for merge ?

**Comment by arnaud-deprez** [comment]
I think so but still waiting for that and the upcoming release

**Comment by ryantenney** [comment]
@arnaud-deprez merged, thanks so much!

**Comment by arnaud-deprez** [comment]
Thank you, you're welcome !

**Pull request merged**
